# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-13 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
